Update for moved resource files
XENONnT/WFSim pull request #68
Opened 2020-12-03 18:15 UTC by zhut19

nT related resource files are being removed from `strax_auxiliary_files` See XENONnT/strax_auxiliary_files#9 and XENONnT/private_nt_strax_aux_files#1

2020-12-03 18:20 UTC, ramirezdiego commented
@zhut19 Notice the repo is now called `private_nt_aux_files`.

2020-12-03 18:25 UTC, zhut19 commented
Ah, right, thank you @ramirezdiego. But I should wait a bit for that pr merge, so this can pass the travis test.

2020-12-16 11:06 UTC, jorana requested changes

2020-12-16 11:06 UTC, jorana commented on wfsim/load_resource.py
> +                'photon_ap_cdfs': 'xnt_pmt_afterpulse_config.pkl.gz',
This looks certainly useful to change

2020-12-16 11:06 UTC, jorana commented on wfsim/load_resource.py
> +            url_base = f'https://raw.githubusercontent.com/XENONnT/private_nt_aux_files/{commit}/sim_files'
This does not work as it is a private github repository. We should revert this and use the solution I propose in #69

2020-12-21 20:14 UTC, zhut19 commented
Close as this is completely covered by #69

2020-12-21 20:14 UTC, closed without merging